import 'package:flutter/material.dart';

import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'South Indian',
    color: Colors.purple,
  ),
  Category(
    id: 'c2',
    title: 'Gujrati',
    color: Colors.red,
  ),
  Category(
    id: 'c3',
    title: 'Rajasthani',
    color: Colors.orange,
  ),
  Category(
    id: 'c4',
    title: 'Punjabi',
    color: Colors.amber,
  ),
  Category(
    id: 'c5',
    title: 'West Bengali',
    color: Colors.blue,
  ),
  Category(
    id: 'c6',
    title: 'Chinese',
    color: Colors.green,
  ),

];

const DUMMY_MEALS = const [
  Meal(
    id: 'm1',
    categories: [
      'c1',
    ],
    title: 'Masala Dosa',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://hommaderecipes.files.wordpress.com/2015/05/masala-dosa.jpg',
    duration: 30,
    ingredients: [
      '2 cup parboiled rice',
      '1/2 cup urad dal',
      '1 teaspoon salt',
      '1/4 cup refined oil',
      '1/2 teaspoon fenugreek seeds',
      '1/2 kilograms boiled potato',
      '2 medium chopped green chilli',
      '1 tablespoon mustard seeds',
      '1/4 teaspoon turmeric',
      'salt as required',
      '1 1/2 cup sliced onion',
      '2 tablespoon refined oil',
      '10 leaves curry leaves',
      '1/4 cup water',
    ],
    steps: [
      'Prepare the batter and ferment overnight',
      'Prepare the potato filling for Masala Dosa',
      'Pan fry your dosa on a dosa tawa',
      'Add filling and fold the dosa',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c1',
    ],
    title: 'Idli Sambhar',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'http://i.ndtvimg.com/i/2016-02/idli_625x350_61455181315.jpg',
    duration: 25 ,
    ingredients: [
     'Ingredients -2 cup Rice',
     '1 cup urad Dal',
     'Salt',
     'Coconut CHATNI : 1 Coconut',
     '1/2 cup Peanuts',
     '2 green chilly',
     'Salt',
     '1/2 cup Curd',
     'green Coriander',
     'SAMBHAR : 1 cup Toor Dal',
     '1 cup mixed veggies',
     '2 tsp Tamarind paste',
     'Salt',
     '1/2 spoon red chilly powder',
     '2 tbsp Everest sambhar Masala',
     'Asafoetida - 1/4 th tsp',
     '1/2 tsp mustard seeds',
     '1/2 methi dana',
     'kadi patta',
     'Dry red chillies - 2',
     'refined oil/ghee',
    ],
    steps: [
      'for the idlis, soak the rice and dal for 8-10 hours, then strain and grind them into a smooth paste. whisk with hand and leave it overnight to ferment. The next day, add required amount of salt.',
      'Then heat idli steamer, grease the cavities of the idli plate and pour little batter into each of them. Steam them 10-12 minutes, demould and serve.',
      'For the coconut chutney, blend everything except the curd in a blender, then take it out into a bowl, heat some oil and add mustard seeds and curry leaves, once they splutter, add this tempering to the chutney and serve.',
      'To make the sambar, soak the toor dal overnight. Then boil them along with the vegetables in some water, in a pressure cooker, the next morning, and keep aside.',
      'Then heat a pan with some oil. Then add the mustard seeds, fenugreek seeds, dry red chillies and curry leaves. Then add the chilly powder , sambar masala powder and salt.',
      'Cook for few minutes and then add the boiled dal and vegetables. Then add the tamarind paste and water. Boil and simmer for sometimes. check for seasoning and then serve with idli and chutney.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c1',
    ],
    title: 'Uttapam',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://i.ndtvimg.com/i/2017-10/uttapam-recipes_806x605_81507637803.jpg',
    duration: 40,
    ingredients: [
      'Fat grains of rice  ------ 300 grams',
      'Urad dal  ------ 100 grams',
      'Salt ------ add to taste',
      'Baking Soda ----- 1/2 tsp',
      'Tomatoes  ------ 250 grams',
      'Rie ------ 2 tsp',
      'Oil ------ 1/2 cup',
    ],
    steps: [
      'Clean Dal - rice, wash the two and soak in water for 4-5 hours',

      'Grind Dal in a mixer to make a fine paste and keep it in  bowl. Now grind the rice grains and mix with dal(Do not make a very fine paste of the rice grains). Add salt, baking soda to this mix and blend well. The mixture should be thick such that when dropped from a height it falls in lumps. Cover this mixture allowing it to ferment',

      'You will see that the mixture has doubled in quantity. Stir it using a spoon. The mixture needed to prepare Uttapam is ready. Mixture for Dosa and Idli is also prepare in this way.',

      'Chop tomatoes into small pieces.',

      'Place a non stick Tawa(flat pan) on the gas and heat. Pour 2 tsp oil in the Tawa. Put 2-3 pinch Rie and fry it. Now put 1 tbsp tomato and spread it in a circle 2 inches in diameter. Now  pour 2 tbsp mixture over the tomato spread. Spread the mixture in a circle 5-6 inches in diameter and thick. Pour some oil all around the Uttapam and all pour some on it(if the mixture seems too thick then add little water and make it thin so that mixture can be spread easily on the Tawa). Decrease the flame, cover Uttapam with a plate allowing it to cook. In almost 2-3 minutes the lower base of the Uttapam turns brown after getting cooked. With a ladle overturn the Uttapam and cook this side for another 2 minutes. You can see that this side has also become brown. Your Uttapam is ready to eat. Prepare Uttapam in this way with the remaining mixture.',
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c1',
    ],
    title: 'Appam',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://somethingiscookingdotcom.files.wordpress.com/2014/08/appam.jpg',
    duration: 120,
    ingredients: [
      '1 kilograms boiled rice',
      '4 cup water',
      'salt as required',
      '1 teaspoon dry yeast',
      '2 cup grated coconut',
      '1 teaspoon sugar',
    ],
    steps: [
      'Appam is a delectable South Indian recipe, which can be prepared in a few minutes if all the ingredients are in place. Here’s how you prepare this delicious dish. Take a large bowl and soak 1 kilogram of rice in it for about 5 hours and then drain out the water from the bowl.',
      'Once the rice is soaked, put a pressure cooker on medium flame and add the soaked rice in it along with 2 and a half cup of water. Close the lid and pressure cook the rice for 1 whistle. Once cooked, let the steam release on its own and open the lid',
      'Now, take a blender and prepare a mixture of cooked rice and grated coconut. Then take a bowl and add sugar, dry yeast, salt and water. Leave the mixture unattended for half an hour. After half an hour, mix both the mixtures well and combine them together. Let the batter ferment for about 8-9 hours and your Appam batter will be ready.',
      'Put a pan on medium flame and spread the mixture in it. Now cover the pan with a lid and heat for 3-4 minutes, then reduce the flame to low. The appam is now ready, enjoy it with your choice of curry.',
      'Appams are undoubtedly one of the best South Indian breakfasts. Though this recipe looks very simple and easy, there are a few things that you should take care of while cooking. 1. The batter should be made using the finest quality rice such as pachari. 2. Make sure you ferment the rice for at least 8-10 hours or overnight. 3. If you do not have yeast in your home, you can use coconut water for fermentation purposes. It will also make appam tastier than ever. 4. We have used cooked rice for the batter, as it makes the Appam soft and delicious.',

    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c2'
    ],
    title: 'Khandvi',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://farm6.static.flickr.com/5128/5357022715_9a76c90279.jpg',
    duration: 25,
    ingredients: [
     'Gram flour (besan) – 1 cup or 100 gm',
     'Sour buttermilk or chaas – 3 cup',
     'Salt – 2/3 teaspoon or add as required',
     'Oil – 1 tablespoon',
     'Mustard seeds (rai) – 1 teaspoon',
     'Green chilli chopped – 1 teaspoon',
     'Freshly grated coconut – 2 tablespoon',
     'Chopped coriander leaves (dhania patta)- 2 tablespoon',
    ],
    steps: [
      'Take buttermilk in a saucepan or a broad frying pan',
      'Now add the gram flour/ besan. With a wired whisk, keep on stirring and mixing till all the lumps are dissolved and you get a smooth batter. There should be no lumps in the batter',
      'Add salt to this mixture. Mix well',
      'Now at this stage you can put this frying pan on the stove top and keep the flame lowest to medium. And begin to stir with a spatula.',
      'Keep on stirring when the khandvi batter is getting heated up. Lumps will begin to form & you have to continuously stir so that the lumps don’t form.',
      'The batter would thicken and keep on thickening. Keep on stirring',
       'It usually took around 17-20 minutes on low flame to get required consistency. But the timing will vary depending in the intensity of the flame, the thickness/thinness of the pan and the size of the pan.',
       'The batter also should not be allowed to stick at the bottom. So you have to stir continuously. The consistency that we require is shown in the figure below.',
       'Do a plate test when the batter has thickened well.',
       'Spread a few teaspoons of batter on the greased plate. Let it cool a bit and then begin to roll. If you are unable to roll, then the batter needs to be cooked more.',
       'Grease plate with oil before spreading the batter over it so that our roll doesn’t get stick to the base. When the cooking is done then you have to quickly pour about 1/2 to 2/3 cup of batter on a large greased plate and spread thinly and evenly with a spatula. You have to be quick with the remaining batter too. Since even a bit of cooling and the batter becomes like a blob, difficult to spread ( although these blob of khandvi will also taste good that remained sticks afterwards 😉 ) But you have to be quick to get rolls of khandvi.',
       'Gently roll each strip tightly. Then place them in a serving tray or plate. ',

    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c2',
    ],
    title: 'Dhokla',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://www.jagranimages.com/images/07_2015-khaman-dhokla.jpg',
    duration: 40,
    ingredients: [
      'Cup gram flour',
      '1 tbsp citric acid',
      '1 tbsp sugar',
      'to taste salt',
      'A pinch of turmeric',
      'Water',
      '1 tbsp fruit salt/ baking powder',
      '1 tbsp oil',
      '1/2 tbsp mustard seeds',
      '1 Dried red chilli',
      '7-8 Curry leaves',
    ],
    steps: [
      'In a bowl mix gram flour, citric acid, salt, sugar and turmeric. Add water and make it into a smooth batter with medium thick consistency.',
      'In a glass add the fruit salt or baking powder. Add water to it and pour this into the dhokla mixture.',
      'Grease the steaming tin with 2 drops of oil and pour the mixture into it. Steam for about 15-20 minutes or till cooked.',
      'In a pan, add oil, mustard seeds, curry leaves and red chillies. Let it splutter.',
      'Pour the tadka over the prepared dhokla.',
      'Cut into pieces and serve.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c2',
    ],
    title: 'Undhiyu',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://www.rasoimenu.com/wp-content/uploads/2019/06/Gujarati-Undhiyu-Recipe.jpg',
    duration: 75,
    ingredients: [
      'Beans - 200gms',
      'Small brinjal - 5'
      'Small potato - 8',
      'Raw banana - 1',
      'Sweet potato - 1',
      'Yam - 100gms',
      'Oil - 4-5 tbsp',
      'Heeng (asafoetida) - 2 pinch',
      'Ajwain (Carom seeds) - 1/2 tsp',
      'Salt - add to taste',
      'Turmeric powder - 1/2 tsp',
      'Red chilli powder - 1/4-1/2 tsp',
      'Coriander powder - 2 tsp',
      'Aamchur (Dried mango powder) - 1/2 tsp',
      'Garam masala - 1/2 tsp',
      'Powdered sugar - 1/2 tsp',
      'Sesame seeds - 2 tbsp',
      'Peanuts - 2 tbsp',
      'Cashew nuts - 2 tbsp',
      'Ginger(grated) - 2 inch long strip',
      'Green chilli(chopped) - 2-3',
      'Coriander(fine chopped) - 1 cup',
      'Lemon - 1',
      'Gramflour- 1/3 cup',
      'Wheat flour - 1/3 cup',
      'Salt - add to taste',
      'Dhania (Coriander powder) - 1/2tsp',
      'Red chilli powder - less than 1/4 tsp',
      'Turmeric powder - less than 1/4 tsp',
      'Methi (Fenugreek) - 1/2 cup',
      'Oil - to fry Muthiya',
    ],
    steps: [
      'First to make masala, take peanuts and sesame seeds in a grinder. Grind into powder.',
      'Take it into a bowl. Add desiccated coconut.',
      'Add remaining ingredients (chopped coriander leaves, grated ginger, chopped chilies, green garlic, red chili powder, salt, sugar, lemon juice).',
      'Mix well till it gets incorporated. And keep it aside. NOTE: Instead of chopping chilies, coriander and all separately, take all the masala ingredients into the grinder or food processor, pulse it till you get coarse grinded mixture.',
      'Prepare all the veggies. Below in the back fresh pigeon peas and surti papadi. At front, left to right - Yam (suran), Purple yam (kand or ratalu), sweet potatoes',
      'Make cross slit to potatoes and small eggplants and stuff it with prepared masala. This use all the masala, you will have much leftover we will use in the recipe later.',
      'Heat the oil in a pressure cooker, once hot add add pigeon peas and papdi.',
      'Add yam, purple yam and sweet potatoes with extra masala. Mix well.',
      'Add water, mix, and check salt. Gently add stuffed veggies. After adding these do not stir otherwise masala will come out. Cover it and let it cook for 2 whistles on medium-high heat.',
      'While it is pressure cooking, let’s make methi muthia. Wash the methi leaves very well. I have kept them in cold water for 15 minutes, so all the dirt will settle down at the bottom, then I took leaves, squeeze extra water gently using hand.',
      'Take atta, besan, salt, sugar, turmeric, chili powder with ginger paste and green chilies in a bowl. Mix it.',
      'Add 3 tablespoons of oil. Rub it into flour with fingertips.',
      'Then add washed fenugreek leaves and lemon juice.',
      'Again mix it with hands.',
      'Start making dough by adding little water at a time. Sometimes you might not need any water to make dough.',
      'Grease your hand with little oil and make small sized muthias like this.',
      'Heat the oil to deep or shallow fry and meanwhile it is getting ready, shape all the muthias same way. While shaping them it starts to stick to your hand then wash hands, again grease and shape.',
      'Now oil is hot, fry the muthias.',
      'Keep moving them around for even browning. Fry till they are crisp and golden brown from all sides.',
      'Then drain the extra oil using slotted spatula.',
      'Remove it to the paper towel lined plate. Keep it aside till needed.',
      'Let the pressure go down itself then open the cover, it will look like this and you will have nice aroma.',
      'Add fried muthia and simmer for 5 minutes on medium-low heat. I have removed it to other pan because my pressure cooker is too small and so I was not able to mix properly. Garnish with coriander leaves. It is ready to serve.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c2',
    ],
    title: 'Fafda',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'http://www.salebhai.com/Themes/salebhai/Content/images/dussehra/fafda.png',
    duration: 45,
    ingredients: [
      '1 cup besan',
      '2 1/2 tbsp oil',
      '1/2 tbsp carom seeds',
      '1 tsp papad khar',
      'salt to taste',
      'oil for deep frying',
    ],
    steps: [
     'Combine all ingredients in a deep bowl and mix well',
     'Knead into a soft dough using enough water till smooth',
     'Take a small portion of dough and roll into a 50mm cylindrical roll in between your palms',
     'Place it on the flat surface and with your palm stretch it from one end to other with low force to make it long and straight',
     'losen the strip gently',
     'now heat the oil in the non stick pan and deep fry till it turns crispy nut not brown',
     'cool it and serve',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c2',
    ],
    title: 'Patra',
    affordability: Affordability.Affordable,
    complexity: Complexity.Simple,
    imageUrl:
        'https://foodnhealth.org/wp-content/uploads/2016/03/Patra-Recipe.jpg',
    duration: 40,
    ingredients: [
      'FOR BATTER',
      'Gram Flour / Besan / Kadalai Mavu - 1½ cup',
      'Red Chilli Powder - 1 tblsp',
      'Salt to taste',
      'Turmeric Powder - 1 tsp',
      'Jaggery / Gur - 3 tblsp',
      'Tamarind Pulp - 3 tblsp',
      'Ginger Paste - 1 tblsp',
      'Oil - 1 tblsp',
      'Water as needed',
      'FOR SEASONING',
      'Oil - 2 tblsp',
      'Mustard Seeds / Kaduku - 1 tsp',
      'Cumin Seeds / Jeerakam - ½ tsp',
      'Sesame Seeds / Ellu / Til - 2 tblsp',
      'Curry Leaves - 1 sprig',
    ],
    steps: [
      'Mix all ingredients to a smooth thick batter.',
      'Take arbi leaves and remove the thick stalk.',
      'Take each leaf spread batter on top place another leaf and repeat the same.',
      'Roll it tight.',
      'Steam it for 30 mins.',
      'Cool it and cut into pieces.',
      'Now heat oil in a pan, add in mustard, cumin and sesame seeds and let it sizzle.',
      'Add the sliced arbi roll and cook till light golden.',
      'Serve hot.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: false,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c3',
    ],
    title: 'Gatte Ki Subzi',
    affordability: Affordability.Affordable,
    complexity: Complexity.Hard,
    imageUrl:
        'https://flavorverse.com/wp-content/uploads/2017/01/Gatte-Ki-Sabzi-Authentic-Rajasthani-Food.jpg',
    duration: 50,
    ingredients: [
      'FOR GATTE',
      '1 cup besan / gram flour',
      '1/2 tsp coriander seeds, crushed',
      '1/4 tsp ajwain / carom seeds',
      '1/4 tsp turmeric',
      '1/4  tsp kashmiri red chilli powder',
      'pinch hing / asafoetida',
      '1/4 tsp salt',
      '2 tbsp ghee / clarified butter',
      '2 tbsp curd / yogurt',
      '2 tbsp water',
      'FOR SABZI:',
      '2 tbsp oil',
      '1 tsp cumin / jeera',
      '1 tsp kasuri methi / dry fenugreek leaves',
      '1 bay leaf / tej patta',
      '1/2 tsp fennel / saunf',
      'pinch hing / asafoetida',
      '1 onion, finely chopped',
      '1 tsp ginger garlic paste',
      '1/4 tsp turmeric',
      '1 tsp  kashmiri red chilli powder',
      '1/2 tsp coriander powder',
      '1/4 tsp cumin powder / jeera powder',
      '1 cup curd / yogurt, whisk',
      '1/2 tsp salt',
      '1/4 tsp garam masala',
      '2 tbsp coriander, finely chopped',
    ],
    steps: [
      'firstly, in a large kadai heat 2 tbsp oil and saute spices.',
      'further, add 1 onion, 1 tsp ginger garlic paste and saute to golden brown.',
      'keeping the flame on low, add spices and saute well.',
      'furthermore, add 1 cup water and 1 cup curd. stir continuously until the mixture comes to a boil.',
      'now add prepare gatte (gram flour dumplings) and 1/2 tsp salt. mix well.',
      'cover and boil for 5 minutes.',
      'additionally, add 1/4 tsp garam masala and 2 tbsp coriander. mix well.',
      'finally, serve gatte ki sabji with roti, phulka or naan.',
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  ),
  Meal(
      id: 'm11',
      categories: [
        'c3',
      ],
      title: 'Ker Sangri',
      affordability: Affordability.Affordable,
      complexity: Complexity.Hard,
      imageUrl:
          'https://mediaindia.eu/wp-content/uploads/2017/03/Cusine.png',
      duration: 40,
      ingredients: [
        '1/2 tablespoon ker',
        'salt as required',
        '1/8 teaspoon carom seeds',
        '1 tablespoon red chilli powder',
        '1 teaspoon coriander powder',
        '1/2 teaspoon raisins',
        '1 dry red chili',
        '1/2 kilograms green beans',
        '2 tablespoon vegetable oil',
        '1/8 teaspoon asafoetida',
        '1/8 teaspoon powdered turmeric',
        '1/2 teaspoon dry mango powder',
        'water as required',
      ],
      steps: [
        'Place the pressure cooker on full flame and pour some water in it along with the ker, green beans and salt. Mix well and cover with a lid. Cook till 3 whistles and then keep it aside for some time.',
        'Now, place a nonstick pan over medium flame and pour vegetable oil in it. Once the oil is hot enough, add red chili powder, asafoetida, chopped dry red chili and carom seeds in it. Saute for a minute.',
        'Pour the pressure cooked mixture prepared in the first step into the pan along with salt, raisins, dry mango powder, coriander powder and turmeric powder. Cook well for 2-4 minutes on medium flame.',
        'Your kair sangri is now ready to be served. Transfer it to a separate bowl and enjoy with your family and friends.',
      ],
      isGlutenFree: true,
      isVegan: true,
      isVegetarian: true,
      isLactoseFree: true,
    ),
    Meal(
          id: 'm12',
          categories: [
            'c3',
          ],
          title: 'Raab',
          affordability: Affordability.Affordable,
          complexity: Complexity.Simple,
          imageUrl:
              'https://pandareviewz.com/wp-content/uploads/2019/02/baajra-raab-sandesh.jpg',
          duration: 20,
          ingredients: [
            '2 tablespoons Bajra Flour',
            '1 tablespoons Whole Wheat Flour',
            '1/4 teaspoon Dry ginger powder , or freshly ground ginger',
            '1/4 cup Jaggery , crumbled',
            '2 teaspoons Ghee',
            '1/2 teaspoon Ajwain (Carom seeds) , or cumin seeds',
            '1 teaspoon Whole Black Peppercorns , pounded',
          ],
          steps: [
           'To begin making the Raab Recipe; combine the bajra, wheat flour and 3 cups of water in a saucepan and place it on medium heat. Stir to make sure there are no lumps.',
           'Stir in the jaggery, ginger powder and allow the mixture to come to a boil stirring constantly. Continue to stir until the mixture begins to thicken slightly for about 5 to 8 minutes.',
           'Heat the ghee in another small pan; add the ajwain (or cumin), black pepper and allow it to roast for a few seconds.',
           'Pour the ghee into the hot Raab Mixture. Check the taste and add more jaggery or ginger to suit your taste. You can adjust the consistency by adding water if required.',
          ],
          isGlutenFree: true,
          isVegan: true,
          isVegetarian: true,
          isLactoseFree: true,
        ),
        Meal(
                  id: 'm13',
                  categories: [
                    'c3',
                  ],
                  title: 'Ghevar',
                  affordability: Affordability.Affordable,
                  complexity: Complexity.Simple,
                  imageUrl:
                      'https://www.cookforindia.com/wp-content/uploads/2016/08/ghevar.jpg',
                  duration: 35,
                  ingredients: [
                   '1 1/2 cup all purpose flour',
                   '2 pieces ice cubes',
                   '1/4 cup milk',
                   '1/2 cup ghee',
                   '1/2 cup ghee',
                   '2 1/2 cup water',
                   '1/8 teaspoon edible food color',
                   '1 cup sugar',
                   '1/2 teaspoon powdered green cardamom',
                   '1 strand saffron',
                   '1/2 tablespoon chopped almonds',
                   '6 inches silver vark',
                  ],
                  steps: [
                    'take a large wide bowl and add solidified ghee in it. Take one ice cube at a time and rub the ghee vigorously. Take more ice cubes as required, till the ghee becomes very white in colour.',
                    'Then add milk, flour and one cup water. Mix these ingredients to make a smooth batter. Dissolve colour in some water and add to the batter. Add more water as required. The consistency of the batter should be fairly thin in texture.',
                    'Then take an aluminium or steel cylindrical container. Make sure that its height is at least 12″ and diameter is of 5-6″. Fill half of the container with ghee. Heat it and once the ghee is hot enough, then take a 50 ml, glassful of the batter. Pour in centre of ghee, slowly in one continuous thread like stream. Allow the foam to settle.',
                    'Pour one more glassful in hole formed in centre. When the foam settles again, loosen the Ghevar with an iron skewer inserted in hole. Lift carefully, at a slant and place on wire mesh to drain. Keep hot syrup in a wide flat-bottomed container to fit in the Ghevar. Then, dip the Ghevar in it and remove it to drain out the excess syrup. Then, keep aside on a mesh, this will take out the extra syrup.',
                    'Alternatively, pour some syrup evenly all over, keeping Ghevar in a mesh placed over a container. Let it cool and settle down, then top it with silver foil. Splash a few drops of saffron milk, sprinkle some chopped dry fruits and a few pinches of cardamom powder. Serve it with savouries like Pakoras, Kachoris and Samosas.',

                  ],
                  isGlutenFree: false,
                  isVegan: true,
                  isVegetarian: true,
                  isLactoseFree: false,
                ),
                Meal(
                                  id: 'm14',
                                  categories: [
                                    'c3',
                                  ],
                                  title: 'Bajra Ki Roti with Lasun Chutney',
                                  affordability: Affordability.Affordable,
                                  complexity: Complexity.Simple,
                                  imageUrl:
                                      'https://c3.staticflickr.com/9/8274/29691111210_eb5123335a_o.jpg',
                                  duration: 35,
                                  ingredients: [
                                   'Bajra Roti:',
                                   '1 cup Bajra Flour',
                                   '1/2 cup wheat flour',
                                   '2 tbsp kasoori methi',
                                   'salt to taste',
                                   'warm water – to knead',
                                   'Lasun Chutney:',
                                   '3 big garlic cloves – peeled',
                                   '1/2 tbsp red chili powder',
                                   '1 tbsp lemon juice',
                                   'salt to taste',
                                  ],
                                  steps: [
                                    'Bajra Roti:',
                                    'Sieve bajra, wheat and salt. Combine flour and kasoori methi in a mixing bowl. Add water little by little and knead to smooth dough.',
                                    'If you add more water then dough will become sticky. Just add little water to form dough. Keep it aside for 10 mins.',
                                    'Heat a tava or frying pan on medium flame. Divide dough into 4 equal balls. Take a greased plastic sheet or banana leaf. Flatten each balls using your fingers to form a thick disc. I have made little thin disc.',
                                    'Place roti on tava and fry till both the sides turn golden brown. You can also apply little oil/ghee over roti.',
                                    'Lahsun Chutney:',
                                    'Blend all the ingredients in a mixer to smooth paste. Add little water while blending. Serve with Bajra Roti. Store the remaining in refrigerator.',

                                  ],
                                  isGlutenFree: false,
                                  isVegan: true,
                                  isVegetarian: true,
                                  isLactoseFree: true,
                                ),
                Meal(
                                                  id: 'm15',
                                                  categories: [
                                                    'c4',
                                                  ],
                                                  title: 'Sarson Ka Saag Aur Makki Ki Roti',
                                                  affordability: Affordability.Affordable,
                                                  complexity: Complexity.Hard,
                                                  imageUrl:
                                                      'https://i.ndtvimg.com/i/2018-01/saag_620x330_41515666560.jpg',
                                                  duration: 105,
                                                  ingredients: [
                                                   'Ingredients for making Sarson Ka Saag:',
                                                   '1 kg Mustard Leaves',
                                                   '500 gm Spinach leaves',
                                                   '1 inch Ginger',
                                                   '2-3 Green chilli',
                                                   '1 cup Makki ka atta',
                                                   '1 tbsp Vegetable oil',
                                                   '1 cup Onion',
                                                   '1/2 tbsp Red Chili powder',
                                                   '1 tbsp Garlic paste',
                                                   'Salt',
                                                   'Ingredients for Makki Ki Roti:',
                                                   '400 gm Makki ka atta',
                                                   '1/2 tbsp Crushed Carom seeds',
                                                   '1/2 tbsp Salt',
                                                   'Water',
                                                   'oil for shallow frying',
                                                  ],
                                                  steps: [
                                                  'Instructions for making Sarson Ka Saag:',
                                                  'Take mustard leaves and spinach roughly chopped.',
                                                  'Then wash chopped mustard leaves and spinach at least 3-4 time to remove all impurities.',
                                                  'When all greens are properly clean then take the pressure cooker and put all washed greens into the cooker.',
                                                  'Add salt, 1-inch ginger, 2 green chilli into the cooker',
                                                  'Cover the pressure cooker and wait for 3 whistles after that let the greens cook on low flame.',
                                                  'When greens are cooked and cool it down then add maize flour and blend it with blender and make it smooth.',
                                                  'Take another pan and heat oil',
                                                  'Add 1 cup finely chopped onions, 1tbsp of garlic paste, 1 1/2 chopped ginger and 1 chopped green chilli into the pan',
                                                  'Then add 1/2 tbsp of red chili powder and mix it',
                                                  'when temper oozing oil then pour a purred green into the pan, mix it well',
                                                  'leave the pan on low flame and stir occasionally',
                                                  'Sarson ka Saag is ready to serve with Makki ki roti and jaggery',
                                                  'Instructions for Makki Ki Roti:',
                                                  'Take 400gm maize flour',
                                                  'add 1/2 tbsp of salt and crushed carom seeds',
                                                  'add water and make a dough',
                                                  'make medium size balls of dough',
                                                  'sprinkle a wheat flour on the rolling board and place a dough ball on rolling board',
                                                  'then gently roll with a rolling pin (belan), sprinkle flour on top of the chappati if chappati is stuck on rolling board',
                                                  'roll to medium size round circle, this maize flour roti makes not very thin but little thick if you make it thin then possibilities of break roti are increased.',
                                                  'now heat a tawa and spread oil on tawa',
                                                  'after that gently place a makki roti on tawa',
                                                  'when one side is little brown then flip the other side of makki roti',
                                                  'when both sides become brown then your makki roti is ready to serve',

                                                  ],
                                                  isGlutenFree: false,
                                                  isVegan: true,
                                                  isVegetarian: true,
                                                  isLactoseFree: true,
                                                ),
    Meal(
        id: 'm16',
        categories: [
          'c4',
        ],
        title: 'Chole Bhature',
        affordability: Affordability.Affordable,
        complexity: Complexity.Hard,
        imageUrl:
            'http://2.bp.blogspot.com/-w4KOeWh0DXk/UA7pfsmVXhI/AAAAAAAARSk/qAOZ30Zy1AM/s1600/cb+five+s.jpg',
        duration: 80,
        ingredients: [
          'For chole:',
          '2 cup chickpeas',
          '2 tsp oil',
          '1 Bbay leaf',
          '1 Cinnamon stick',
          '3-4 Cloves',
          '1 tsp whole pepper corns',
          '3 Green cardamom',
          '2 Black cardamom',
          '1 tsp rurmeric powder',
          '1 tsp chili powder',
          '1 tsp coriander powder',
          '1 tsp cumin powder',
          '1 tsp cumin seeds',
          '1/2 tsp asafoetida',
          'to taste salt',
          '1 cup onions, chopped',
          '1 cup tomatoes, chopped',
          '1 tsp ginger, chopped',
          '1 tsp garlic, chopped',
          '1 tsp ajwain',
          '1 tsp lime juice',
          '1 green chili, chopped',
          '1 Tea bag',
          '1 tbsp butter',
          'For the bhaturas:',
          '2 cups maida',
          '1/2 tsp yeast',
          '1/2 cup whole wheat flour',
          'A pinch of salt',
          'Water',
          'Oil',
        ],
        steps: [
         'Prepare chole:',
         'In a pan add oil, bay leaf, cinnamon, cumin seeds, cloves, whole pepper corns, green and black cardamom.',
         'After it gets brown add chopped onions and saute it. Now add chopped ginger and garlic.',
         'Followed by turmeric, chili powder, coriander powder, cumin powder, asafoetida and salt, fry the ingredients together well.',
         'For de glazing the pan add a little water.',
         'Now add the chole (soaked overnight and pressure cooked) to the masala.',
         'After stirring well add tomatoes, little sugar and salt to the chole.',
         'Now add ajwain, chopped green chilies and water for the base.',
         'To get the color in the chole, add a tea bag to the masala.',
         'Simmer the chole gently for an hour and cover it.',
         'Add lime juice and a dollop of butter to it.',
         'Garnish the chole with coriander and butter and serve them hot with bhaturas.',
         'Prepare the bhaturas:',
         'Knead the whole wheat flour, maida and salt together with adequate amount of water.',
         'Sprinkle the yeast on top. Leave it for 2-3 hours for the yeast to work.',
         'Divide it into equal portions. Roll out in an oval or round shape.',
         'Deep fry till golden brown, like a puri.',
         'Serve.',
        ],
        isGlutenFree: true,
        isVegan: true,
        isVegetarian: true,
        isLactoseFree: true,
      ),
   Meal(
           id: 'm17',
           categories: [
             'c4',
           ],
           title: 'Dal Makhni',
           affordability: Affordability.Affordable,
           complexity: Complexity.Hard,
           imageUrl:
               'https://i.ndtvimg.com/i/2016-11/dal-makhani_620x350_41478501912.jpg',
           duration: 50,
           ingredients: [
             '2 Cups Sabut urad dal',
             '8 cups Water',
             '2 tbsp Salt',
             '1 tbsp Ginger, sliced',
             '2 tbsp Butter',
             '1 tbsp Oil',
             '2 tsp Shahi jeera',
             '1 tsp Kasoori meethi',
             '2 cups Tomato puree',
             '1 tsp Chilli powder',
             '1 tsp Sugar',
             '1/2 cups Cream',
             'For garnishing Green chillies',
           ],
           steps: [
            'To the dal, add water, 1 Tbsp salt and ginger. Cook until dal becomes tender.',
            'In a heavy based pan, heat butter and oil. Add shahi jeera and kasoori methi. When they begin to splutter, add tomato puree, remaining salt, chilli powder and sugar.',
            'Stir-fry over high flame, till the oil separates.',
            'Add cooked dal and bring to boil. The consistency should be such that the dal should move around freely when stirred, otherwise add a little water.',
            'Leave to simmer, uncovered, till well blended. Stir-in cream and once it gets heated through, serve immediately, garnished with green chillies',
           ],
           isGlutenFree: true,
           isVegan: true,
           isVegetarian: true,
           isLactoseFree: true,
         ),
   Meal(
              id: 'm18',
              categories: [
                'c4',
              ],
              title: 'Paneer Tikka',
              affordability: Affordability.Affordable,
              complexity: Complexity.Hard,
              imageUrl:
                  'https://myfoodstory.com/wp-content/uploads/2017/02/Oven-Baked-Tandoori-Paneer-Tikka-2.jpg',
              duration: 85,
              ingredients: [
                '1/2 Kg paneer',
                '1 tomato',
                '1 onion',
                '1 capsicum',
                'Marinade for paneer tikka:',
                '1/2 tbsp cumin seeds',
                '1/2 tbsp coriander seeds',
                '1 brown cardamom',
                '10 green cardamom',
                '1/2 tbsp cloves',
                '1/2 tbsp black pepper',
                '2 pcs star anise',
                '1/2 tbsp shahee zeera',
                '3 tbsp ginger-garlic paste',
                '2 tsp turmeric powder',
                '2 tsp red chilli powder',
                '2 tsp coriander powder',
                'Salt',
                '2 tsp kashmiri chilli powder',
                '2 tbsp refined oil',
                '1/2 lime',
                '1/2 tbsp dry mango powder',
                '1/2 tbsp chaat masala',
                '2 green chilli, chopped',
                '100 gms curd',
                '1/2 tbsp garam masala',
                'coriander leaves, chopped',
                'mint leaves, chopped',
              ],
              steps: [
              'Marination for paneer tikka:',
              'Dry roast and pound cumin seeds, coriander seeds, brown cardamom, green cardamom, cloves, black pepper, star anise and shahee zeera in a mortar and pestle.',
              'In a bowl add ginger garlic paste, turmeric powder, red chilli powder, coriander powder, salt, kashmiri chilli powder, refined oil, coriander leaves chopped, mint leaves chopped, lime, dry mango powder, chaat masala, green chilli, whisked curd and hara masala. Mix them all.',
              'For grilling paneer tikka:',
              'In a tray spread some paneer cubes, julienne onion, capsicum and tomatoes.',
              'Mix the masala in the tray. Marinate the paneer cubes.',
              'Skewer the tikkas for roasting.',
              'Now keep the marinated paneer tikkas in the fridge for 45 minutes.',
              'Then grill the tikkas till cooked.',
              'Serve the paneer tikka hot',
              ],
              isGlutenFree: true,
              isVegan: true,
              isVegetarian: true,
              isLactoseFree: true,
            ),
   Meal(
                 id: 'm19',
                 categories: [
                   'c5',
                 ],
                 title: 'Bhapaa Aloo',
                 affordability: Affordability.Affordable,
                 complexity: Complexity.Hard,
                 imageUrl:
                     'https://thaimoderntravel.co.th/wp-content/uploads/2018/03/Aloo.jpg',
                 duration: 50,
                 ingredients: [
                   '200 gm small potatoes',
                   '2 tsp mustard oil',
                   '1/2 tsp Bengali five spice mixture',
                   '2 dry red chillies',
                   '1/2 tsp mustard paste',
                   '1 tsp hung curd',
                   '3/4 tsp desiccated coconut paste',
                   'Pinch of green chilli paste',
                   'Pinch of turmeric powder',
                   'Salt - to taste',
                   'Dash of lime juice',
                   '2 banana leaves',
                 ],
                 steps: [
                 'Peel the potatoes and par boil them in salted water, drain and keep aside.',
                 'Heat oil in a non-stick pan, add the five spice mixture, break the red chillies in half and add them next.',
                 'Stir the spices around till they splutter.',
                 'Pour this over the potatoes and put aside',
                 'In a mixing bowl prepare a marinade with the mustard paste, curd, coconut paste, green chilli paste and turmeric powder, whip it well.',
                 'Gently mix the potatoes into this marinade.',
                 'Add the salt and lime juice, mix again.',
                 'Put the potatoes on a steel plate, cover with the banana leaves and steam them for 6-8 minutes. Serve hot.',
                 ],
                 isGlutenFree: true,
                 isVegan: true,
                 isVegetarian: true,
                 isLactoseFree: true,
               ),
  Meal(
                   id: 'm20',
                   categories: [
                     'c5',
                   ],
                   title: 'Baigun Bhajja',
                   affordability: Affordability.Affordable,
                   complexity: Complexity.Hard,
                   imageUrl:
                       'http://2.bp.blogspot.com/-2rKnW3uWmOA/T3FvenzG_xI/AAAAAAAAAkQ/Cc_CUh89N7w/s1600/100_8756.JPG',
                   duration: 55,
                   ingredients: [
                     '3 big eggplants',
                     '1 Tbsp ginger-garlic paste',
                     '2 tsp red chilli powder',
                     '1 tsp turmeric powder',
                     '1 tsp coriander powder',
                     'Salt to taste',
                     'Juice of 2 lemons',
                     '2 onions, chopped',
                     '4 green chillies, chopped',
                     '1 ginger, chopped',
                     '4 Tbsp fresh coriander, chopped',
                     '1 cup mustard oil',
                     '1 tsp garam masala powder',
                     'For the tomato chutney:',
                     '3 tomatoes',
                     '1 tsp ginger, chopped',
                     '1 tsp green chilli, chopped',
                     '2 tsp coriander, chopped',
                     'Salt to taste',
                     '1/2 tsp sugar',
                     'Juice of 1 lemon',
                     '2 tsp mustard oil',
                   ],
                   steps: [
                   'Take two eggplants and clean them well. Slice them in half inch thickness and marinate with ginger garlic paste, red chilli powder, turmeric powder, coriander powder, garam masala powder, salt and lemon juice (1 lemon) and keep it aside.',
                   'Roast the remaining eggplant on cooking range till it is cooked properly.',
                   'Once cooked, peel the skin and roughly chop the eggplant. Mix in chopped onion, green chilli, ginger, fresh coriander, salt and lemon juice',
                   'In a pan, heat some mustard oil on a medium flame and pan fry the marinated eggplant slices till they are cooked.',
                   'Serve it hot with the roasted eggplant.',
                   'For the tomato chutney:',
                   'Boil whole tomato and puree it nicely in mixie.',
                   'Take out in a bowl and add chopped ginger, green chilli, coriander, salt, sugar, lemon juice (1 lemon) and mustard oil.',
                   'Mix well and serve it with the bhajja.',
                   ],
                   isGlutenFree: true,
                   isVegan: true,
                   isVegetarian: true,
                   isLactoseFree: true,
                 ),
  Meal(
                     id: 'm21',
                     categories: [
                       'c5',
                     ],
                     title: 'Chor Chori',
                     affordability: Affordability.Affordable,
                     complexity: Complexity.Simple,
                     imageUrl:
                         'https://i.pinimg.com/736x/8f/6f/ad/8f6fad002061fae5193cc9bcd90efa14--special-occasion-a-bowl.jpg',
                     duration: 35,
                     ingredients: [
                       '4 Tbsp Mustard oil',
                       '4-5 Garlic pods',
                       '2 tsp ginger, chopped',
                       '2 Green chillies',
                       '4 Bay leaves',
                       '1 tsp panch phoran',
                       '1 cup potatoes, chopped',
                       '4 Baby brinjals',
                       '1 cup cauliflower, chopped',
                       '1 cup pumpkin, chopped',
                       'A pinch of salt',
                       'A pinch of sugar',
                       '1/4 tsp turmeric',
                       '1/4 tsp dhania powder',
                       '1/4 tsp zeera powder',
                       '1 Green chilli',
                       'for garnishing Coriander leaves',
                     ],
                     steps: [
                     'Heat the mustard all to remove its bitterness.',
                     'While the mustard oil is burning out (this could take about 5-7 minutes), in a mortar and pestle add some garlic, ginger and 2 green chillies with a pinch of salt.',
                     'Pound them togethar.',
                     'Once done, get back to the mustard oil now.',
                     'Add the tej patta, panch poran and the ginger-garlic paste you just made. Mix.',
                     'Panch poran consists of equal parts of mustard seeds, cumin seeds, fenugreek seeds, fennel seeds and onion seeds).',
                     'First add the potatoes and let them fry on low heat.',
                     'Once they looked half cooked, add the cauliflower.',
                     'Now is also a good time to add salt. Mix well.',
                     'Turn up the heat little bit and sprinkle little water on it.',
                     'Cover and let it steam for about 3-4 minutes.',
                     'Once the potatoes are almost cooked add turmeric, dhania powder and zeera powder.',
                     'Now turn up the heat and add the pumpkin and brinjals.',
                     'Add some salt again along with a slit green chilly.',
                     'Toss it around. Add some water, cover it and let the vegetables cook for a while. (5minutes).',
                     'Now check the pan for the vegetables. Mix and mash them a bit.',
                     'Let it cook for another 4-5 minutes.',
                     'Once vegetables are done, take the chorchori out into a bowl.',
                     'Garnish with coriander leaves.',
                     ],
                     isGlutenFree: true,
                     isVegan: true,
                     isVegetarian: true,
                     isLactoseFree: true,
                   ),
  Meal(
                       id: 'm22',
                       categories: [
                         'c5',
                       ],
                       title: 'Rasgulla',
                       affordability: Affordability.Affordable,
                       complexity: Complexity.Hard,
                       imageUrl:
                           'https://www.indianhealthyrecipes.com/wp-content/uploads/2014/09/rasgulla-recipe.jpg',
                       duration: 50,
                       ingredients: [
                         '2 Litre low fat milk (Refrigerated overnight, boiled',
                         '1/4 cup lemon juice (mixed in 1/4 cup water).',
                         '1 tsp refined flour (maida) or semolina',
                         '4 cups thin sugar syrup (flavored with cardamom or rosewater).',
                       ],
                       steps: [
                       'Remove whatever cream that forms over the milk.',
                       'Bring to a boil, lower heat and add the lemon mixture gradually, till milk curdles.',
                       'Does not matter if you do not use up the whole solution.',
                       'Shut off the heat and leave mixture to rest for 5 minutes.',
                       'Drain off water and leave the paneer in a colander for at least 4 hours.',
                       'Mash paneer very smooth (no grains).',
                       'Add the flour/semolina and mash some more.',
                       'Bring 4-6 cups of water to a boil, and shape the paneer into balls (smooth ones, no cracks) in the mean time.',
                       'Transfer balls into the boiling water, cover with a tight fitting cover and let cook till puffed up (about 20 minutes).',
                       'Let cool, squeeze out of the water, transfer to syrup, chill and serve.',
                       ],
                       isGlutenFree: false,
                       isVegan: true,
                       isVegetarian: true,
                       isLactoseFree: false,
                     ),
  Meal(
                         id: 'm23',
                         categories: [
                           'c6',
                         ],
                         title: 'Manchurian',
                         affordability: Affordability.Affordable,
                         complexity: Complexity.Simple,
                         imageUrl:
                             'https://s3-media3.fl.yelpcdn.com/bphoto/RrYA7xqB0op_lxukTkJ7_g/348s.jpg',
                         duration: 45,
                         ingredients: [
                           'For vegetable balls:',
                           '1/2 Cup Cabbage',
                           '1/2 Cup Carrot',
                           '1/2 Cup Capsicum',
                           '1/2 Cup Spring onion',
                           '1 tsp Ginger',
                           '1 tsp Garlic',
                           '3 Tbsp Corn flour',
                           '2 Tbsp Maida',
                           '2 tsp Salt',
                           '2 tsp Black pepper',
                           '1 tsp Soy sauce',
                           '1 Tbsp Water',
                           'For manchurian sauce:',
                           'Oil',
                           '2 Tbsp Garlic',
                           '1 Tbsp Ginger',
                           '1 tsp Green chilli',
                           '2 Tbsp Spring onion',
                           '2 Tbsp Tomato ketchup',
                           '2 Tbsp Chilly sauce',
                           '1 tsp Soya sauce',
                           '1 tsp Vinegar',
                           '1 1/2 Tbsp Salt',
                           '1 Tbsp Black pepper',
                           '3 Tbsp Corn flour',
                           '1 Cup Water',
                         ],
                         steps: [
                         'To prepare the vegetable balls:',
                         'Take all the veggies, finely chopped, in a bowl along with ginger, garlic, corn flour, maida, salt, black pepper and soy sauce.Veg Manchurian',
                         'Mix them well, adding water as required for consistency.Veg Manchurian',
                         'Make round balls out of the thick vegetable mixture.Veg Manchurian',
                         'Now deep fry the vegetable balls in a pan.Veg Manchurian',
                         'Prepare the sauce:',
                         'Heat some oil in a pan and roast ginger, garlic and green chilli in it for a whileVeg Manchurian',
                         'Add spring onion, tomato ketchup, chilly sauce, soya sauce and vinegar followed by salt and black pepper.Veg Manchurian',
                         'Mix them well and add a mixture of corn flour plus water to the pan.Veg Manchurian',
                         'Mix thoroughly and put the fried vegetable balls into the mixture.Veg Manchurian',
                         'Properly mix the balls along with the sauce.',
                         'Garnish with spring onion and celery. Serve hot along with cooked rice.',
                         ],
                         isGlutenFree: true,
                         isVegan: true,
                         isVegetarian: true,
                         isLactoseFree: true,
                       ),
  Meal(
                           id: 'm24',
                           categories: [
                             'c6',
                           ],
                           title: 'Chowmein',
                           affordability: Affordability.Affordable,
                           complexity: Complexity.Simple,
                           imageUrl:
                               'https://healthynibblesandbits.com/wp-content/uploads/2015/03/Chicken-Chow-Mein-6.jpg',
                           duration: 40,
                           ingredients: [
                             '1 pound ground beef',
                             '1 onion, chopped',
                             '2 stalks celery, chopped',
                             '1/2 cup slivered almonds',
                             '1 cup cooked rice',
                             '1 (10.75 ounce) can condensed cream of chicken soup',
                             '1/2 cup water',
                             '3 tablespoons soy sauce',
                             '5 ounces chow mein noodles',
                           ],
                           steps: [
                           'Preheat oven to 350 degrees F (175 degrees C).',
                           'In a large skillet over medium high heat, saute the ground beef for 5 minutes. Add the onion and celery and saute for 5 more minutes.',
                           'In a separate medium bowl, combine the almonds, rice, soup, water and soy sauce. Mix together well and add to the beef mixture. Place this into a lightly greased 9x13 inch baking dish. Top with chow mein noodles.',
                           'Bake at 350 degrees F (175 degrees C) for 20 minutes.',
                           ],
                           isGlutenFree: true,
                           isVegan: false,
                           isVegetarian: false,
                           isLactoseFree: true,
                         ),
   Meal(
                              id: 'm25',
                              categories: [
                                'c6',
                              ],
                              title: 'Spring Rolls',
                              affordability: Affordability.Affordable,
                              complexity: Complexity.Simple,
                              imageUrl:
                                  'https://recipetineats.com/wp-content/uploads/2017/09/Spring-Rolls-4.jpg',
                              duration: 40,
                              ingredients: [
                                '2 ounces dry soy vermicelli',
                                '4 large eggs eggs, beaten',
                                '1 onion, finely chopped',
                                '2 ounces mushrooms, drained and chopped',
                                '3/4 (4 ounce) can small shrimp, drained and chopped',
                                '1 pound lean ground pork',
                                '2 tablespoons vegetable oil',
                                '1 carrot, shredded',
                                '2 ounces crabmeat',
                                '3 ounces bean sprouts',
                                '2 pinches ground black pepper',
                                '1 tablespoon soy sauce',
                                '3 tablespoons fish sauce',
                                '1 clove garlic, chopped',
                                '20 eaches rice wrappers (6.5 inch diameter).',
                                '1 quart oil for deep frying',
                              ],
                              steps: [
                              'Soak the vermicelli 30 minutes in warm water; drain.',
                              'In a large bowl, mix the vermicelli, eggs, onion, mushrooms, shrimp, pork, vegetable oil, carrot, crabmeat, bean sprouts, pepper, soy sauce, fish sauce and garlic.',
                              'One by one, moisten the rice wrappers with a damp tea towel and fill with 2 to 3 tablespoons of the vermicelli mixture. Roll the wrappers, and allow them to set for 30 minutes.',
                              'In a large saucepan, heat the oil to 375 degrees F (190 degrees C).',
                              'Fry the spring rolls one or two at a time until golden brown, about 3 minutes. Drain on paper towels.',
                              ],
                              isGlutenFree: true,
                              isVegan: false,
                              isVegetarian: true,
                              isLactoseFree: true,
                            ),
  Meal(
                                id: 'm26',
                                categories: [
                                  'c6',
                                ],
                                title: 'Chilli Paneer',
                                affordability: Affordability.Affordable,
                                complexity: Complexity.Simple,
                                imageUrl:
                                    'https://yummyindiankitchen.com/wp-content/uploads/2017/05/how-to-make-chilli-paneer-chilli-paneer-dry.jpg',
                                duration: 40,
                                ingredients: [
                                 '250 gm paneer',
                                 '1 teaspoon soy sauce',
                                 '2 tablespoon tomato ketchup',
                                 'salt as required',
                                 '1 red bell pepper',
                                 '1/2 cup onion',
                                 '1 dash ginger powder',
                                 '1 capsicum (green pepper).',
                                 '1 teaspoon schezwan sauce',
                                 '2 teaspoon ginger',
                                 '2 teaspoon garlic paste',
                                 '2 green chilli',
                                 '1 teaspoon corn flour',
                                 '1 teaspoon vinegar',
                                 '1/2 cup refined oil',
                                 '1 tablespoon green chilli sauce',
                                 '1 yellow bell pepper',
                                 '1 teaspoon butter',
                                ],
                                steps: [
                                'To prepare this yummy appetizer recipe, take a chopping board and chop the paneer, onion and bell peppers in cube sizes. Wash the cubed bell peppers in running water and keep them aside. Now, peel ginger finely chop it in a small bowl. Then cut the green chillies in strips or you can also slice them half.',
                                'Marinate and shallow fry the paneer pieces until golden in colour',
                                'Next, add paneer in a small bowl. Add cornflour, salt, ginger powder, vinegar, chilli paste in it. Marinate for 10-15 minutes. Next, put a skillet on medium flame and heat oil in it. When the oil is hot enough, add the cubed paneer pieces in it and fry them till they turn golden in colour. Once done, keep aside.',
                                'Saute all the veggies with spices and add fried paneer in it',
                                'Now, put a saucepan on medium flame and add a little oil in it. Saute add garlic paste in it, chopped ginger, and slit green chillies in it. Add cubed bell peppers in it, saute for a minute then add onions in it. Next, add Schezwan sauce, tomato ketchup and soy sauce in it. Afterwards, add melted butter in it Stir well and cook for two to three minutes. Finally, add the fried paneer cubes and toss them well. Garnish with spring onions and enjoy hot',
                                'Tips for making restaurant-style Chilli Paneer',
                                'The very first rule for making restaurant-style Chilli Paneer is that you must shallow fry the cottage cheese or paneer. Make sure you don’t over fry the paneer, as it can make it hard and chewy, while it should be soft and melt-in-the-mouth. 2. Before frying the Paneer, you can dip it in the batter of rice-corn flour batter. It will make the paneer crunchy as well as delicious. 3. For making Chilli Paneer, use sesame oil for an authentic Chinese flavour. 4. Cook all the veggies on high heat for that crunchiness.',
                                ],
                                isGlutenFree: true,
                                isVegan: true,
                                isVegetarian: true,
                                isLactoseFree: true,
                              ),
 Meal(
                                 id: 'm27',
                                 categories: [
                                   'c6',
                                 ],
                                 title: 'Fried Rice',
                                 affordability: Affordability.Affordable,
                                 complexity: Complexity.Simple,
                                 imageUrl:
                                     'https://www.pumpkinnspice.com/wp-content/uploads/2018/03/easy-fried-rice-5.jpg',
                                 duration: 20,
                                 ingredients: [
                                   '3 tbsp. sesame oil, divided',
                                   '3 large eggs',
                                   'Kosher salt',
                                   '2 carrots, diced',
                                   '3 green onions, thinly sliced, white and green parts divided',
                                   '3 cloves garlic, minced',
                                   '1 tbsp. peeled and minced ginger (from a 1" piece).',
                                   '4 c. cooked long grain rice (preferably leftover).',
                                   '3/4 c. frozen peas',
                                   '3 tbsp. low-sodium soy sauce',
                                 ],
                                 steps: [
                                 'Heat a large cast iron skillet over high heat until very hot, about 2 minutes. Add 1 tablespoon oil.',
                                 'Beat egg with 2 teaspoons water and a large pinch salt and add to skillet. Cook, stirring to form large soft curds, about 30 seconds. Transfer to a plate.',
                                 'Return skillet to high heat and add 2 tablespoons oil, the carrots, and whites of the green onions. Cook until lightly golden, about 2 minutes. Add garlic and ginger and cook, stirring, until fragrant, 1 minute.',
                                 'Add rice, peas, and cooked eggs to skillet. Pour in soy sauce and cook, stirring until heated through, 1 minute. Season with salt and pepper and stir in the remaining green onions.',
                                 ],
                                 isGlutenFree: true,
                                 isVegan: true,
                                 isVegetarian: true,
                                 isLactoseFree: true,
                               ),
 ];
